name = "sitemap"
main = "index.js"  # 入口文件

[build]
command = "npm install"

[env.production]
bindings = [
  { name = "BOOKS_D1", binding = "D1Database", type = "d1", database_id = "books-data" }
]

compatibility_date = "2024-11-19"