name = "sitemap-generator"
main = "index.js"  # 确保这个文件存在并且是你的入口文件

[build]
command = "npm install"

[env.production]
bindings = [
  { name = "BOOKS_D1", binding = "D1Database", type = "d1", database_id = "books-data" }
]
