name = "sitemap-generator"
type = "module"  # 确保使用模块格式

[build]
command = "npm install"

[env.production]
bindings = [
  { name = "BOOKS_D1", binding = "D1Database", type = "d1", database_id = "books-data" }
]
