name = "sitemap"
main = "worker.js"
compatibility_date = "2024-11-19"

# D1 数据库配置
[[d1_databases]]
binding = "BOOKS_D1"
database_name = "books_data"
database_id = "336d7d02-efee-48a9-bb9d-8bcfe4d974fa"

[dependencies]
jszip = "3.10.1"