name = "sitemap-generator"

[build]
command = "npm install"

[env.production]
bindings = [
  { name = "BOOKS_D1", binding = "D1Database", type = "d1", database_id = "books-data" }
]

# Specify the entry point (script file)
main = "index.js"  # 或者根据你的文件修改为正确的路径
